sudo: false
dist: trusty
language: node_js
node_js:
  - "8"

# BUILD THE APPLICATION
script:
  - export APP_VERSION=$(node -p -e "require('./package.json').version")
  - export APP_CODE=$(node -p -e "require('./package.json').short_name")
  - npm run dist

# DEPLOY TO GITHUB RELEASES
before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git tag $APP_VERSION -a -m "Automated GitHub release for $APP_VERSION"
  - git push -q https://dragonjet:$GITHUB_API_KEY@github.com/shinycolors/hiori --tags
  - mv build/dist/chrome.zip build/dist/$APP_CODE-$APP_VERSION-chrome.zip
  - mv build/dist/firefox.zip build/dist/$APP_CODE-$APP_VERSION-firefox.zip

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_API_KEY
  file:
    - build/dist/$APP_CODE-$APP_VERSION-chrome.zip
    - build/dist/$APP_CODE-$APP_VERSION-firefox.zip
  on:
    tags: false
    branch: master
    condition: $TRAVIS_PULL_REQUEST == "false"
